### ISSUE TITLE
invalid credentials

### ISSUE THREAD

**Issue by buhtz** [jessejensen/ebscopy#8]
I tried to use ebscopy as described in the README but it doesn't work here. I don't really understand what all this arguments are for.

I have account (and are able to log in) on CINAHL (which is one of EBSC databases I 
```Python
#!/usr/bin/env python2
import sys
import ebscopy

session = ebscopy.Session(user_id='MoonKid', password='*****', profile='profile', org='org', guest='n')
results = session.search('nursing research')

results.pprint()
session.end()
sys.exit()
```
But something is wrong with the credentials. What is `profile`, `org` and `guest` for?
Do I really need to login?
```
Traceback (most recent call last):
  File "./ebs.py", line 6, in <module>
    session = ebscopy.Session(user_id='MoonKid', password='*****', profile='profile', org='org', guest='n')
  File "build/bdist.linux-i686/egg/ebscopy/ebscopy.py", line 388, in __init__
  File "build/bdist.linux-i686/egg/ebscopy/ebscopy.py", line 347, in get
  File "build/bdist.linux-i686/egg/ebscopy/ebscopy.py", line 273, in connect
  File "build/bdist.linux-i686/egg/ebscopy/ebscopy.py", line 244, in request
ebscopy.ebscopy.AuthenticationError: Invalid credentials!
```

**Comment by jessejensen** [comment]
The required credentials are set at the institutional level, not per user. The user_ids and passwords are set by someone with access to the EBSCOadmin console. The primary audience for this module is library staff members who wish to build an interface to their licensed EBSCO Discovery Service.

The API does offer [IP Authentication](http://edswiki.ebscohost.com/API_Reference_Guide:_Authentication:_IP_Authentication), but I haven't added that functionality to ebscopy yet.

The profile, guest, and org parameters are required to [create a session](http://edswiki.ebscohost.com/API_Reference_Guide:_Sessions:_CreateSession) with the API. The profiles are also managed via the EBSCOadmin console. The guest value is required so the API knows if the end user has been properly authenticated and is authorized to access certain data. The org value is just an arbitrary string used to identify sessions for reporting.

**Comment by buhtz** [comment]
This means there is no way for "normal" humans to use ebscopy?

**Comment by jessejensen** [comment]
Pretty much. Maybe you could talk to the systems librarian about getting the required access. And if you really need it, I can add IP authentication support to ebscopy. Perhaps you could describe what you're trying to accomplish with the module.

**Comment by buhtz** [comment]
Thanks for helping. What is the difference between profile-methode or the IP-Auth methode?
Would be IP-Auth a methode I could use if my librarian has no access to the EBSCHOST?

The librarian of my university told me that the EBSCHOST-access have to be paid extra - but they don't.
